#!/usr/bin/env node

var katex = require("./katex.min.js");
var input = "";

var args = process.argv.slice(2);

process.stdin.on("data", function(chunk) {
    input += chunk.toString();
});

process.stdin.on("end", function() {
    var options = { displayMode: args.indexOf("--display-mode") !== -1 };
    var output = katex.renderToString(input, options);
    console.log(output);
});
